name: Update data

on:
  schedule:
    - cron:  '33 3 * * *' # daily at 03:33
  workflow_dispatch:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libraries
        run: sudo apt-get install -y xmlstarlet

      - name: Fetch latest data
        run: bin/fetch.sh

      - name: Generate CSV
        run: |-
          # Escape quote " for CSV with double qoutes "", then add quote on the beginning & end of the line
          while read line; do echo -e "\"${line//\"/\"\"}\""; done <tmp-spolky.txt >tmp-spolky-quoted.txt
          # Assemble CSV and sort records
          paste -d"," tmp-spolky-quoted.txt tmp-ico.txt tmp-ids.txt | sort -f -V >tmp-datovky.csv
          # Assmble final CSV with HEADER
          echo '"Spolek","IČO","ID datové schránky"'>datovky.csv
          cat tmp-datovky.csv >>datovky.csv

          # Sort values also for spolky.txt and ids.txt
          cat tmp-spolky.txt | sort -f -V >spolky.txt
          cat tmp-ids.txt | sort >ids.txt

      - name: Update count
        run: |-
          DS_COUNT=$(cat spolky.txt | wc -l)
          # Update count in count.txt
          echo $DS_COUNT>count.txt
          # Update in README
          sed -E -i "s/(Aktuální počet DS: )([0-9]+)/\1$DS_COUNT/" README.md
          # Add today record to history.csv if not exists
          TODAY=$(date -u "+%F")
          sed -i -n -e '/^'$TODAY',/!p' -e '$a'$TODAY,$DS_COUNT history.csv

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install Python dependencies
        run: pip install graph-cli numpy==1.23.5

      - name: Update history graph
        run: graph history.csv -o history.png -X "" -Y "" -T "Počet datových schránek Pionýra a jeho pobočných spolků" --xtick-angle 45 --figsize 1600x1000  --fill --yrange 90 --legend ""

      - name: Commit and push if changed
        run: |-
          rm tmp-*
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --cached
          TIMESTAMP=$(date -u "+%F %T %Z")
          git commit -m "Latest data: ${TIMESTAMP}" || exit 0
          git push
