name: Update data

on:
  schedule:
    - cron:  '33 3 * * *' # daily at 03:33
  workflow_dispatch:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libraries
        run: sudo apt-get install -y xmlstarlet

      - name: Fetch latest data
        run: |-
          curl -s -o tmp-search.xml -d '<SearchSubjectRequest xmlns="http://seznam.gov.cz/ovm/ws/v1"><Nazev>Pionýr, z. s.</Nazev></SearchSubjectRequest>' -H 'Content-Type: application/xml' -X POST https://www.mojedatovaschranka.cz/sds/ws/call
          cat tmp-search.xml | xmlstarlet sel -N n="http://seznam.gov.cz/ovm/ws/v1" -t -v "//n:NazevOsoby[starts-with(.,'Pion')]" >spolky.txt
          echo "" >>spolky.txt # add newline at the end
          cat tmp-search.xml | xmlstarlet sel -N n="http://seznam.gov.cz/ovm/ws/v1" -t -v "//n:NazevOsoby[starts-with(.,'Pion')]/following-sibling::n:ISDS" >ids.txt
          echo "" >>ids.txt # add newline at the end

      - name: Generate CSV
        run: |-
          # Escape quote " for CSV with double qoutes "", then add quote on the beginning & end of the line
          while read line; do echo -e "\"${line//\"/\"\"}\""; done < spolky.txt >tmp-spolky-quoted.txt
          echo '"Spolek","ID datové schránky"'>datovky.csv
          paste -d"," tmp-spolky-quoted.txt ids.txt >>datovky.csv

      - name: Update count
        run: |-
          DS_COUNT=$(cat datovky.csv | wc -l)
          echo $DS_COUNT>count.txt
          sed -E -i "s/(Aktuální počet DS: )([0-9]+)/\1$DS_COUNT/" README.md

      - name: Commit and push if changed
        run: |-
          rm tmp-*
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff --cached
          timestamp=$(date -u "+%F %T %Z")
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
